apiVersion: v1
kind: Service
metadata:
  name: mqttsender-service
  labels:
    run: mqttsender
spec:
  type: NodePort
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mqttsender
