apiVersion: v1
kind: Service
metadata:
  name: mqttreceiver-service
  labels:
    run: mqttreceiver
spec:
  type: NodePort
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mqttreceiver
