apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqttsender-deployment
spec:
  selector:
    matchLabels:
      app: mqttsender
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mqttsender
    spec:
      containers:
      - name: mqttsender
        image: mqtt_sender:v1
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
        securityContext:
          privileged: true
      volumes:
      - name: dev-video0
        hostPath:
           path: /dev/video0
        
